### PR TITLE
Upgrade to Lean v4.4.0

### PR DESCRIPTION
**Pull request by monsterkrampe**
I fixed the version in `lean-toolchain` now to avoid unpleasant surprises in the future. We should upgrade this somewhat regularly though :)

### CODE REVIEW

**Review by matzemathics — APPROVED** [review]
Looks good, should I the nix-fix here or do you want to merge as-is?

**Comment by monsterkrampe** [comment]
@matzemathics feel free to do the fix here :)

**Comment by mmarx** [comment]
Please run `nix fmt` as well, or at least update the formatter if you want to use something other than `alejandra`.

**Comment by matzemathics** [comment]
@mmarx any ideas  what might be wrong in the nix build? It seems to me as if the lean flake is broken 😕.

**Comment by mmarx** [comment]
I'll take a look.

**Comment by mmarx** [comment]
> @mmarx any ideas what might be wrong in the nix build? It seems to me as if the lean flake is broken 😕.

The problem is that `ProofWidgets4` fails to build, because it has some custom logic in its `lakefile.lean` that builds Javascript from Typescript. `buildLeanPackage` doesn't do this, so it fails when the code tries to include those non-existing Javascript files. Not sure what the easy way to fix this would be, though.

**Comment by monsterkrampe** [comment]
Will merge without the nix changes for now and create a new draft PR for them.

**Pull request merged**
